package com.example.academiaumb.model.dao;

import org.greenrobot.greendao.annotation.*;

import com.example.academiaumb.model.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVIDAD".
 */
@Entity(active = true)
public class Actividad {

    @Id
    private Long id;
    private String Nombre;
    private java.util.Date FechaEntrega;
    private Double Nota;

    @NotNull
    private String tipo;

    @NotNull
    private String categaria;
    private Long AsignaturaId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ActividadDao myDao;

    @ToOne(joinProperty = "AsignaturaId")
    private Asignatura asignatura;

    @Generated
    private transient Long asignatura__resolvedKey;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Actividad() {
    }

    public Actividad(Long id) {
        this.id = id;
    }

    @Generated
    public Actividad(Long id, String Nombre, java.util.Date FechaEntrega, Double Nota, String tipo, String categaria, Long AsignaturaId) {
        this.id = id;
        this.Nombre = Nombre;
        this.FechaEntrega = FechaEntrega;
        this.Nota = Nota;
        this.tipo = tipo;
        this.categaria = categaria;
        this.AsignaturaId = AsignaturaId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActividadDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public java.util.Date getFechaEntrega() {
        return FechaEntrega;
    }

    public void setFechaEntrega(java.util.Date FechaEntrega) {
        this.FechaEntrega = FechaEntrega;
    }

    public Double getNota() {
        return Nota;
    }

    public void setNota(Double Nota) {
        this.Nota = Nota;
    }

    @NotNull
    public String getTipo() {
        return tipo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTipo(@NotNull String tipo) {
        this.tipo = tipo;
    }

    @NotNull
    public String getCategaria() {
        return categaria;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategaria(@NotNull String categaria) {
        this.categaria = categaria;
    }

    public Long getAsignaturaId() {
        return AsignaturaId;
    }

    public void setAsignaturaId(Long AsignaturaId) {
        this.AsignaturaId = AsignaturaId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Asignatura getAsignatura() {
        Long __key = this.AsignaturaId;
        if (asignatura__resolvedKey == null || !asignatura__resolvedKey.equals(__key)) {
            __throwIfDetached();
            AsignaturaDao targetDao = daoSession.getAsignaturaDao();
            Asignatura asignaturaNew = targetDao.load(__key);
            synchronized (this) {
                asignatura = asignaturaNew;
            	asignatura__resolvedKey = __key;
            }
        }
        return asignatura;
    }

    @Generated
    public void setAsignatura(Asignatura asignatura) {
        synchronized (this) {
            this.asignatura = asignatura;
            AsignaturaId = asignatura == null ? null : asignatura.getId();
            asignatura__resolvedKey = AsignaturaId;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
