package com.example.academiaumb.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANEXO".
*/
public class AnexoDao extends AbstractDao<Anexo, Long> {

    public static final String TABLENAME = "ANEXO";

    /**
     * Properties of entity Anexo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Titulo = new Property(1, String.class, "titulo", false, "TITULO");
        public final static Property AsignaturaId = new Property(2, Long.class, "asignaturaId", false, "ASIGNATURA_ID");
    }

    private DaoSession daoSession;

    private Query<Anexo> asignatura_AnexosQuery;

    public AnexoDao(DaoConfig config) {
        super(config);
    }
    
    public AnexoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANEXO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITULO\" TEXT," + // 1: titulo
                "\"ASIGNATURA_ID\" INTEGER);"); // 2: asignaturaId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANEXO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Anexo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String titulo = entity.getTitulo();
        if (titulo != null) {
            stmt.bindString(2, titulo);
        }
 
        Long asignaturaId = entity.getAsignaturaId();
        if (asignaturaId != null) {
            stmt.bindLong(3, asignaturaId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Anexo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String titulo = entity.getTitulo();
        if (titulo != null) {
            stmt.bindString(2, titulo);
        }
 
        Long asignaturaId = entity.getAsignaturaId();
        if (asignaturaId != null) {
            stmt.bindLong(3, asignaturaId);
        }
    }

    @Override
    protected final void attachEntity(Anexo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Anexo readEntity(Cursor cursor, int offset) {
        Anexo entity = new Anexo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // titulo
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // asignaturaId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Anexo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitulo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAsignaturaId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Anexo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Anexo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Anexo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "anexos" to-many relationship of Asignatura. */
    public List<Anexo> _queryAsignatura_Anexos(Long asignaturaId) {
        synchronized (this) {
            if (asignatura_AnexosQuery == null) {
                QueryBuilder<Anexo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AsignaturaId.eq(null));
                asignatura_AnexosQuery = queryBuilder.build();
            }
        }
        Query<Anexo> query = asignatura_AnexosQuery.forCurrentThread();
        query.setParameter(0, asignaturaId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAsignaturaDao().getAllColumns());
            builder.append(" FROM ANEXO T");
            builder.append(" LEFT JOIN ASIGNATURA T0 ON T.\"ASIGNATURA_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Anexo loadCurrentDeep(Cursor cursor, boolean lock) {
        Anexo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Asignatura asignatura = loadCurrentOther(daoSession.getAsignaturaDao(), cursor, offset);
        entity.setAsignatura(asignatura);

        return entity;    
    }

    public Anexo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Anexo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Anexo> list = new ArrayList<Anexo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Anexo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Anexo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
