package com.example.academiaumb.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANOTACION".
*/
public class AnotacionDao extends AbstractDao<Anotacion, Long> {

    public static final String TABLENAME = "ANOTACION";

    /**
     * Properties of entity Anotacion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Detalle = new Property(1, String.class, "detalle", false, "DETALLE");
        public final static Property UrlImagen = new Property(2, String.class, "urlImagen", false, "URL_IMAGEN");
        public final static Property UrlVoz = new Property(3, String.class, "urlVoz", false, "URL_VOZ");
        public final static Property UrlVideo = new Property(4, String.class, "urlVideo", false, "URL_VIDEO");
        public final static Property AnexoId = new Property(5, Long.class, "anexoId", false, "ANEXO_ID");
    }

    private DaoSession daoSession;

    private Query<Anotacion> anexo_AnotacionesQuery;

    public AnotacionDao(DaoConfig config) {
        super(config);
    }
    
    public AnotacionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANOTACION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DETALLE\" TEXT," + // 1: detalle
                "\"URL_IMAGEN\" TEXT," + // 2: urlImagen
                "\"URL_VOZ\" TEXT," + // 3: urlVoz
                "\"URL_VIDEO\" TEXT," + // 4: urlVideo
                "\"ANEXO_ID\" INTEGER);"); // 5: anexoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANOTACION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Anotacion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String detalle = entity.getDetalle();
        if (detalle != null) {
            stmt.bindString(2, detalle);
        }
 
        String urlImagen = entity.getUrlImagen();
        if (urlImagen != null) {
            stmt.bindString(3, urlImagen);
        }
 
        String urlVoz = entity.getUrlVoz();
        if (urlVoz != null) {
            stmt.bindString(4, urlVoz);
        }
 
        String urlVideo = entity.getUrlVideo();
        if (urlVideo != null) {
            stmt.bindString(5, urlVideo);
        }
 
        Long anexoId = entity.getAnexoId();
        if (anexoId != null) {
            stmt.bindLong(6, anexoId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Anotacion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String detalle = entity.getDetalle();
        if (detalle != null) {
            stmt.bindString(2, detalle);
        }
 
        String urlImagen = entity.getUrlImagen();
        if (urlImagen != null) {
            stmt.bindString(3, urlImagen);
        }
 
        String urlVoz = entity.getUrlVoz();
        if (urlVoz != null) {
            stmt.bindString(4, urlVoz);
        }
 
        String urlVideo = entity.getUrlVideo();
        if (urlVideo != null) {
            stmt.bindString(5, urlVideo);
        }
 
        Long anexoId = entity.getAnexoId();
        if (anexoId != null) {
            stmt.bindLong(6, anexoId);
        }
    }

    @Override
    protected final void attachEntity(Anotacion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Anotacion readEntity(Cursor cursor, int offset) {
        Anotacion entity = new Anotacion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // detalle
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // urlImagen
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // urlVoz
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // urlVideo
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // anexoId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Anotacion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDetalle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUrlImagen(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrlVoz(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUrlVideo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAnexoId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Anotacion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Anotacion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Anotacion entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "anotaciones" to-many relationship of Anexo. */
    public List<Anotacion> _queryAnexo_Anotaciones(Long anexoId) {
        synchronized (this) {
            if (anexo_AnotacionesQuery == null) {
                QueryBuilder<Anotacion> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AnexoId.eq(null));
                anexo_AnotacionesQuery = queryBuilder.build();
            }
        }
        Query<Anotacion> query = anexo_AnotacionesQuery.forCurrentThread();
        query.setParameter(0, anexoId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAnexoDao().getAllColumns());
            builder.append(" FROM ANOTACION T");
            builder.append(" LEFT JOIN ANEXO T0 ON T.\"ANEXO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Anotacion loadCurrentDeep(Cursor cursor, boolean lock) {
        Anotacion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Anexo anexo = loadCurrentOther(daoSession.getAnexoDao(), cursor, offset);
        entity.setAnexo(anexo);

        return entity;    
    }

    public Anotacion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Anotacion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Anotacion> list = new ArrayList<Anotacion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Anotacion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Anotacion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
